package cl.envaflex.codes;

public enum NotaVentaEnum {
	
	ESTADO_VENTA_COTIZ ,
	ESTADO_VENTA_NOTA_VENTA_INICIAL ,
	ESTADO_VENTA_NOTA_VENTA_ANULADA,
	ESTADO_VENTA_NOTA_VENTA_DESPACHO,
	ESTADO_VENTA_NOTA_VENTA_CERRADA;
	
}
